services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend/nextdoorbuddy
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/nextdoorbuddy/src:/app/src

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: user
      POSTGRES_DB: nextdoorbuddy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
