version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend/nextdoorbuddy
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/nextdoorbuddy/src:/app/src
