services:
  backend:
    build: ./backend
    container_name: nextdoorbuddy-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/dist:/app/dist
      - uploads_data:/app/uploads
    command: npm run dev
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=rootpass
      - DB_NAME=nextdoorbuddy
<<<<<<< HEAD
      - MONGODB_URI=mongodb://mongodb:27017/journal
      - MONGODB_DB=journal
=======
      # Email Configuration
      
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=doorbudy@gmail.com
      - SMTP_PASS=jymi ameu shij siys 
      - FROM_EMAIL=noreply@doorbudy.cloud
      - FROM_NAME=DoorBudy
      # Verification Settings
      - VERIFICATION_CODE_EXPIRY=15
      - MAX_VERIFICATION_ATTEMPTS=3
      - MAX_RESEND_ATTEMPTS=3
>>>>>>> prod
    depends_on:
      - db
      - mongodb
    networks:
      - nextdoorbuddy-network

  frontend:
    build: ./frontend/nextdoorbuddy
    container_name: nextdoorbuddy-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/nextdoorbuddy/src:/app/src
      - ./uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - nextdoorbuddy-network

  db:
    image: postgis/postgis:15-3.3
    container_name: nextdoorbuddy-db
    restart: always
    ports:
      - "0.0.0.0:5432:5432"  # Expose to all interfaces
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: user
      POSTGRES_DB: nextdoorbuddy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - nextdoorbuddy-network

  mongodb:
    image: mongo:7.0
    container_name: nextdoorbuddy-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: journal
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - nextdoorbuddy-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nextdoorbuddy-network


volumes:
  db_data:
  mongodb_data:
  uploads_data:

networks:
  nextdoorbuddy-network:
    driver: bridge
